name: 04 – Using Actions
on: 
  push:

jobs:
  build:
    runs-on: lab_runner
    defaults:
      run:
        working-directory: /home/student/gha/CWICZENIA/04-praca-z-zewnetrzymi-akcjami/react-app
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7
      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: '24.x'
      - name: Install Dependencies
        run: npm ci --include=dev
      - name: run test
        run: npm test
      - name: build
        run: npm run build