name: 05 – 1 – Event Filters and Activity Types
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  echo:
    runs-on: lab_runner
    steps:
      - name: echo notification
        run: echo "Running whenever a PR is opened or synchronized AND base branch is main."
