name: 05 – 1 – Event Filters and Activity Types
on: 
  workflow_dispatch:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]
#    types: [opened, synchronize]

jobs:
  echo:
    runs-on: lab_runner
    steps:
      - name: echo notification
        run: echo "Running whenever a PR is opened or synchronized AND base branch is main."
